kind: Service
apiVersion: v1
metadata:
  name: demo_project
  labels:
    app: demo_project
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: demo_project
  type: LoadBalancer